version: "3.8"
services:
  db:
    image: 'postgres:13'
    container_name: 'db'
    networks:
      - backend
    env_file: ./env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: 'chrome'
    networks:
      - backend
    ports:
      - '4444:4444'
      - '7900:7900'
    privileged: true
    shm_size: 2g
    restart: unless-stopped

  e-learning:
    build: .
    container_name: 'e-learning'
    image: 'e-learning:1'
    command: >
      sh -c 'cd src &&
             poetry run python3 manage.py migrate --no-input &&
             poetry run python3 manage.py createadmin &&
             poetry run python3 manage.py collectstatic --noinput &&
             poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8080 '
    networks:
      - backend
    volumes:
      - app_static:/service/src/static
      - app_media:/service/src/media
    env_file:
      - ./env/.e-learning.env
    restart: unless-stopped
    depends_on:
      - db
      - chrome

  web_server:
    image: 'nginx:alpine3.18'
    container_name: 'web_server'
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - app_static:/srv/static
      - app_media:/srv/media
    ports:
      - '80:80'
    restart: unless-stopped
    depends_on:
      - e-learning

networks:
  backend:

volumes:
  postgres_data:
  app_static:
  app_media:
