# Generated by Django 4.2.8 on 2023-12-12 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
