# Generated by Django 4.2.8 on 2023-12-14 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="subject",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-created"], name="courses_cou_created_6f51ad_idx"
            ),
        ),
    ]
