# Generated by Django 4.2.8 on 2023-12-14 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_course_options_subject_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ("-created",)},
        ),
    ]
