# Generated by Django 4.2.8 on 2023-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_subject_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ("title",)},
        ),
    ]
