# Generated by Django 4.2.8 on 2023-12-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_module_alter_subject_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
